# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph7fmTe7IPNDEdIhi44KtZ6c7bJSGZoc
"""

pip install --user -U nltk

from nltk.corpus import brown

import nltk
nltk.download('punkt')
nltk.download('wordnet')

from nltk.chat.util import Chat, reflections

pairs = [
    [
        r"my name is (.*)",
        ["Hello %1! How can I help you today?",]
    ],
    [
        r"what is your name?",
        ["My name is ChatBot and I'm here to assist you.",]
    ],
    [
        r"how are you",
        ["I'm doing well, thank you! How about you?",]
    ],
    [
        r"sorry (.*)",
        ["No problem, I understand. How can I assist you?",]
    ],
    [
        r"quit",
        ["Goodbye! Have a great day.",]
    ],
]

def chatbot():
    print("Hello! I'm your NLTK-based chatbot. Type 'quit' to exit.")
    chat = Chat(pairs, reflections)
    chat.converse()

if __name__ == "__main__":
    chatbot()

